PolymerElements/iron-overlay-behavior

iron-overlay-behavior.html
@cdata PTAL cc @notwaldorf 
Prevents doing extra work when the overlay starts closed.
=> don't call _openedChanged if initially closed

iron-overlay-behavior.html
We have a good reason for doing what would otherwise be a noop accessor here, this just tells the compiler that.
=> Suppress compiler warnings about suspicious code

iron-overlay-behavior.html
This is so that the compiler doesn't attribute the @param annotation to be referencing the next line (listeners in this case)
=> Move @event declarations to bottom of prototype

iron-overlay-manager.html, test/iron-overlay-behavior.html
This distinction prevents a sequence of unending execution due to
separate overlays opening and closing in close proximity to each other.
Fixes #31
=> Current overlay is always the latest `opened` one

bower.json, demo/index.html, demo/simple-overlay.html, test/iron-overlay-behavior.html
Fixes the generic usage of `paper-styles.html` and `/deep/` classes and uses the specific imports instead. Also updates the test to the new `wct#^3.4.0` way
=> stop bringing in the paper-styles kitchen sink

iron-overlay-behavior.html, test/iron-overlay-behavior.html
Fixes #60 by waiting for element to be attached to call `this._openChanged`. Only on attached we can safely compute the element's position.
Fixes #57 by using `MockInteractions.tap` :balloon:
=> Compute position on attached

iron-overlay-behavior.html, test/iron-overlay-behavior.html
Fixes #62 by stopping immediate propagation of the event so that only one overlay gets closed on ESC.
=> esc closes only one overlay

iron-overlay-behavior.html
Fixes PolymerElements/iron-menu-behavior#40.
=> IronOverlayBehavior no longer needs click events to bubble to determine when to close.

iron-overlay-behavior.html, test/iron-overlay-behavior.html
Fixes https://github.com/PolymerElements/paper-dialog/issues/68 and https://github.com/PolymerElements/paper-dialog/issues/77
`iron-overlay-behavior` needs to refit itself only once when opened.
=> cleanup _squelchNextResize

iron-overlay-backdrop.html, iron-overlay-behavior.html, iron-overlay-manager.html, test/iron-overlay-behavior.html
Fixes #78 by adding an observer for `with-backdrop` changes.
`iron-overlay-manager` has a specific method to get the `z-index` for backdrop. This is done to make sure that backdrop's index is just below the first opened overlay that has `with-backdrop = true`. Also, its `trackBackdrop()` method now checks for duplicates and ensures that the passed element is opened and has a backdrop.
`iron-overlay-backdrop` will handle the call to `complete()` right after the transition ends. In addition, it updates its `z-index` on `prepare()` and on `close()`.
`iron-overlay-behavior` has been cleaned accordingly.
=> update backdrop on with-backdrop changes

iron-overlay-behavior.html, iron-overlay-manager.html, test/iron-overlay-behavior.html, test/test-overlay2.html
Bug described in #73. This pull request adds the failing tests. 
My approach in #74 is flawed and therefore re-created the tests without the solution. Let's discuss what a reasonable approach to the solution would be. I think that @valdrinkoshi is right, we shouldn't have multiple backdrops, we should only allow one backdrop and that should be managed by the `iron-overlay-manager`.
**EDIT** I've now commited the solution, much more elegant and straightforward: don't allow more than 1 instance of `iron-overlay-backdrop` and let the manager handle the creation of that.
=> Bugfix: backdrop not shared in different elements, causing inconsistent closing

iron-overlay-behavior.html, test/iron-overlay-behavior.html
Fixes #27  by making sure `canceled` is set before updating `opened` (so that `closingReason` will be properly setup). 
Remove setting default value for booleans `canceled, withBackdrop, noAutoFocus, noCancelOnEscKey, noCancelOnOutsideClick`. 
Remove event listeners immediately after `opened` changes, and add them asynchronously if `opened = true`.
`_onCaptureKeydown` will not stop the event propagation but instead check if it is the current overlay (ensures the top one is closed)
=> code cleanup & better handling event listeners 

iron-overlay-backdrop.html, iron-overlay-behavior.html, test/iron-overlay-behavior.html
Fixes https://github.com/PolymerElements/paper-dialog/issues/77 by updating the manager's `backdrops` array on open changed.
Without this fix, when we add transitions to an overlay, it might be that they take longer than the animation of the backdrop. The manager needs to be updated as soon as possible so that once the backdrop is done, it can safely rely on the `manager.getBackdrops()` to be of the right length
=> immediately track backdrop on opened changes

iron-overlay-backdrop.html, test/iron-overlay-behavior.html
Fixes #83 by checking for css `transitionDuration` when closing the backdrop and calling `complete()` if duration is `0s`
Fixes #96 by checking of css `opacity` when closing the backdrop and calling `complete()` if `opacity` is already 0.
Updated previous test that was relying on disabling the animations.
=> call complete() if transitionDuration = 0s

bower.json, demo/index.html, iron-overlay-behavior.html, test/iron-overlay-behavior.html, test/test-buttons.html
Fixes #88 by listening to focus changes on document.
`with-backdrop` will set the `tabindex` to `-1` so that focus can be trapped within the overlay.
=> with-backdrop traps focus within overlay

iron-overlay-manager.html
This helps compilers to understand that `_backdropElement` is a valid property of the manager.
=> define property in constructor

iron-overlay-behavior.html, test/iron-overlay-behavior.html
Fixes #69 by passing the source event to the close functions and the iron-overlay-canceled event.
=> Fixes #69 by passing the original click event to the cancel  function 

test/iron-overlay-behavior.html
Separate tests in their suites:
- basic overlay
- opened overlay
- focus handling
- overlay with backdrop
- multiple overlays
- z-ordering
- multiple overlays with backdrop
- a11y
Create utility methods to listen to events only once.
Use less instances of `test-fixture`
=> test cleanup

iron-overlay-behavior.html, test/iron-overlay-behavior.html
Added tests for `no-auto-focus` property. Discovered "funky" behavior on Safari where if an element with `autofocus` attribute is displayed for the first time, it will receive the focus (tested with `button`, see example here http://jsbin.com/woroci/2/). So now `iron-overlay-behavior` handles also that case, making sure that the element is blurred synchronously after `overlay.open()` gets called.
=> add no-auto-focus test

bower.json, demo/index.html, iron-overlay-behavior.html, test/iron-overlay-behavior.html
Fixes #49, fixes #97 by setting `tabindex=-1` to all overlays so they can be focusable and ensuring `iron-resize` is called before `iron-overlay-opened`. Moreover we now call `notifyResize()` before `_applyFocus()` so that we are sure `refit()` will make the overlay visible (setting `display`).
Additionally, we attach the node change observer only once.
The demo page now looks like this:
=> a11y & prettify demo page

bower.json, iron-overlay-behavior.html, test/iron-overlay-behavior.html
Fixes #105 
We now wrap the focus for overlays `with-backdrop`. Respects `tabindex` too! :tada: 
Moreover, we also focus the first focusable element if there is no `[autofocus]` element.
=> Wrap focus in overlays with backdrop

iron-overlay-behavior.html
Fixes #103, final result is:
Also, moved docs at the bottom otherwise we would have duplicates (see https://elements.polymer-project.org/elements/iron-overlay-behavior#event-iron-overlay-canceled)
=> update events docs

iron-overlay-behavior.html, test/iron-overlay-behavior.html
revert the auto focusing of the first focusable element, since it is a breaking change (introduced in https://github.com/PolymerElements/iron-overlay-behavior/pull/106) that no-one asked.
=> remove autofocus of first element

demo/index.html, iron-overlay-behavior.html, iron-overlay-manager.html, test/iron-overlay-behavior.html
Fixes #94 by storing the external focused element in the manager. Added `restore-focus-on-close` property.
~~Depends on https://github.com/Polymer/polymer/pull/2717~~
=> set focus back to last focused element on close

test/iron-overlay-behavior.html
Fixes tests failing on master (most likely introduced by the latest version of `iron-fit-behavior`). We now allow 1px of delta when checking the position of overlays.
=> allow 1px of delta when checking position

iron-overlay-behavior.html, test/iron-overlay-behavior.html
Fixes #113 by calling `refit` on `_prepareRenderedOpened`. Moreover limit the calls to `notifyResize` when the animation is ongoing; also in `_onIronResize` callback, we don't call `refit` if the animation is not done yet. Updated tests accordingly.
This helps fixing issues like [this one on `iron-dropdown`](https://github.com/PolymerElements/iron-dropdown/pull/63#issuecomment-187840348): what happens there is that `_prepareRenderOpened` calls only `fit`, so it won't recalculate the position information when `opened` changes. This PR makes sure we call `refit` right when (and only when) it is needed.
=> call notifyResize only when not animating. Call refit only once on opened changes.

test/iron-overlay-behavior.html
Fixes tests on master, currently failing because of the new version of chai (the method `isObject` doesn't like anymore `Element`)
=> check for truthy (isObject not reliable with Element)

iron-overlay-behavior.html, iron-overlay-manager.html
The manager currently uses string literals to define getters for certain properties. This is a problem when compilers rename the properties, because string literals won't be modified.
To solve this, rather than using `Object.defineProperty` (which requires a string for the property name), we return an object and define the properties like:
```javascript
var o = {
get prop(){
return 'foo';
}
```
Moreover, we now use an IIFE; this allows not to expose the class, and to make private properties methods really private/contained in the scope of the IIFE.
This PR makes it impossible to access to private objects (e.g. `Polymer.IronOverlayManager._overlays`), but all these were meant to be private so this should not be considered a breaking change.
=> no string literals in IronOverlayManager

iron-overlay-backdrop.html, iron-overlay-behavior.html, test/iron-overlay-behavior.html
Fixes #132 by ensuring `backdropElement` is closed right away on overlay `detached`. Also, `iron-overlay-backdrop` will have `pointer-events: none` when `opened = false`. This allows user interactions while the backdrop is animating :tada:
=> close backdrop on detached

iron-overlay-backdrop.html, iron-overlay-behavior.html, iron-overlay-manager.html, test/iron-overlay-behavior.html
Fixes #109, fixes #117 by handling click and focus listeners on `iron-overlay-manager`.
Previously, each overlay would have these listeners, and these were toggled a tick after `_onOpenedChanged` (to avoid the triggering click event to close them). This was cumbersome because we'd have a lot of listeners, and each overlay would check if it is the `currentOverlay`.
Now, `iron-overlay-manager` will always listen for `click` and `focus`, and delegates the actions only to the current/top overlay (does also some other safety checks). To avoid the immediate closing, we delay the setting of `currentOverlay` for a tick. This fixes also #117.
Finally, we synchronously update the `_overlays`, so that we are sure the array will always contain opened overlays. This allowed to remove `_backdrops`. …
=> Click, focus, keydown listeners on manager

iron-overlay-behavior.html, iron-overlay-manager.html
`iron-overlay-behavior` does not import `iron-a11y-keys-behavior` anymore, neither uses this behavior (key listeners were moved to `iron-overlay-manager`).
Updated jsdoc for how the `rootTarget` is meant to be used in manager's `_onCaptureClick`
=> remove a11y-keys behavior from overlay-behavior. Update jsdoc for rootTarget usage

iron-overlay-behavior.html, iron-overlay-manager.html, test/iron-overlay-behavior.html
Fixes #129 by ensuring `_overlays` gets updated synchronously when an `overlay.opened` changes.
Added new method to the manager, `bringToFront` which is useful to bring an overlay on top; it accepts both numbers (more efficient) and elements (more ergonomic for the Polymer user) as input.
=> avoid duplicates when adding overlays

iron-overlay-behavior.html
The 1ms delay was previously needed for toggling listeners, but since they're now handled in the manager, `_openedChangedAsync` can return to be a micro-task.
=> make _openedChangedAsync a microtask

iron-overlay-manager.html, test/iron-overlay-behavior.html, test/test-menu-button.html
Rather than traversing the parent tree starting from a node, we use `event.path` to have the composed tree, in order to safely recognize who's the deepest overlay in that tree.
=> use path to correctly handle composed tree

demo/index.html, iron-overlay-behavior.html, iron-overlay-manager.html, test/iron-overlay-behavior.html
Fixes #3 by implementing `always-on-top` property.
- the overlay with `always-on-top` should match the `Polymer.IronOverlayManager.currentOverlay()` even if other overlays are opened after it
- if there is more than one overlay with `always-on-top`, the last one to be opened wins (is on top)
- `with-backdrop` doesn't affect `always-on-top`
=> always-on-top implementation

iron-overlay-manager.html
Since `event.path` can be either `null` or `undefined`, accept these values as input by setting a default.
=> Update jsdoc: Accept null & undefined

iron-overlay-behavior.html, iron-overlay-manager.html, test/iron-overlay-behavior.html
Fixes #99, fixes #135 by using `requestAnimationFrame` instead of `async`. 
Also, removed unnecessary setting of `display: ''` followed by `display: none`, and then again `display: ''`. It is enough to just make the overlay visible, calculate its size, and then `requestAnimationFrame` will cause the relayout. 
Tested the patch on `paper-dialog` with animations, it doesn't flash in any of the tested browsers (chrome, firefox, safari).
Also, reset `z-index` only on `_finishRenderClosed`, so that the overlay is on top during its animation, and goes "behind" only when is invisible. This makes the dialog animations much better because a dialog with backdrop doesn't suddenly go back the backdrop when closed.
#135 gets fixed because we don't need to set `offsetWidth` to itself anymore.
=> use requestAnimationFrame for non-blocking animations

iron-overlay-manager.html, test/iron-overlay-behavior.html
Fixes #147 by listening to `touchstart` (touch devices) or `mousedown` rather than `tap/click`.
As a consequence, gestures like dragging outside the dialog cause the dialog to cancel, which is nice for elements like `iron-dropdown` on cases where the user selects text outside the dropdown, causing the dropdown to close.
=> listen to touchstart or mousedown

iron-overlay-behavior.html, test/iron-overlay-behavior.html, test/test-overlay.html
Fixes animation issue for `paper-toast` and `iron-dropdown` happening with the latest `iron-overlay-behavior` (on master). `paper-toast` would not translate when opened, and `iron-dropdown` would blink on safari.
Added `use strict`; did the `display` flipping only on opened (saves a `refit`!). Moved the `_prepareRenderOpened` method (which does the `refit` & `display` flipping) into the `requestAnimationFrame`, for optimal performance.
=> ensure reflow for smooth animations

iron-overlay-backdrop.html, test/index.html, test/iron-overlay-backdrop.html
Any reason why `vh` was used instead of `%`?
Should resolve issue #149
=> fix: bug with iron-overlay-backdrop when on-screen keyboard is shown

iron-overlay-behavior.html, iron-overlay-manager.html
Closure compiler doesn't recognize `cancelAnimationFrame`, so change it to `window.cancelAnimationFrame` (while at it, also `window.requestAnimationFrame`).
Also, the compiler won't recognize the property `alwaysOnTop` for `overlay` (which is of type `Element`), so create a separate method `_shouldBeBehindOverlay` that will tell the compiler to not check the type. While at it, updated the `@param` of other methods to mandate a non-null input.
=> Fix closure compiler issues

iron-overlay-behavior.html, test/iron-overlay-behavior.html
Fixes #158.
`iron-overlay-behavior` was calling `requestAnimationFrame` before it was actually attached to the dom. This would put it in a weird status that might cause wrong bounds calculation (e.g. for `iron-dropdown`). Since elements extending this behavior might memoize position information to save relayouts, those memoized values would end up being wrong (because calculated before the element is actually attached). These wrong calculations end up being different according to the browser, so long story short: wait to be attached, then render opened!
=> defer _renderOpen/_renderClose after attached

iron-overlay-manager.html, test/iron-overlay-behavior.html
Fixes #160 by calling `event.preventDefault()` for overlays with backdrop. This ensures that click/tap events don't go beyond the `backdropElement`.
=> withBackdrop prevents click outside

iron-overlay-behavior.html
Fixes #163, now looks like this:
=> update event docs

iron-overlay-backdrop.html, iron-overlay-behavior.html, iron-overlay-manager.html, test/iron-overlay-behavior.html
`iron-overlay-backdrop` now allows to set `opened` synchronously, and animation to `opened` state is handled with a css class instead of attribute, using `requestAnimationFrame` for better performance.
Removed the dependency to `iron-overlay-manager` as it was needed to limit when the backdrop can be opened or not. This part is controlled by the manager itself now.
`iron-overlay-behavior` delegates the updates of `backdropElement`'s `opened` state to `iron-overlay-manager`.
=> Move backdrop updates to manager

iron-overlay-behavior.html
Like for `renderOpened`, we want also `renderClosed` to have non-blocking animations, so I moved it into the `requestAnimationFrame`
=> call renderClosed inside requestAnimationFrame too

iron-overlay-behavior.html, test/iron-overlay-behavior.html
Fixes #170 by preventing event default and forcing the focus to wrap instead of relying on focus change.
=> force focus wrapping

iron-overlay-behavior.html, test/iron-overlay-behavior.html, test/test-menu-button.html
Fixes #172 by checking `deepActiveElement` instead of `_focusedChild`. 
In `dom=shadow`, `IronOverlayManager` won't see the focus changes in other shadow roots, just the ones happening in the `document` root.
=> check for deepest active element

iron-overlay-behavior.html, test/iron-overlay-behavior.html, test/test-overlay2.html
Fixes #176 by invoking `_focusableNodes` after the overlay is opened instead of during nodes changes.
What was happening previously is that `_focusedNodes` would be called **before** the getter could be overridden by `_onNodesChange`. 
Now, we update the first & last focusable each time an overlay is opened.
Ideally we should have two properties for first and last focusable nodes and deprecate/remove `_focusableNodes`, but that might be a breaking change, while this can qualify as a patch.
=> _focusableNodes can be overridden.

iron-overlay-behavior.html, iron-overlay-manager.html, test/iron-overlay-backdrop.html, test/iron-overlay-behavior.html
Revert #148 since it caused more issues (e.g. #174) than solving problems. Had to do this manually as #148 cannot be automatically reverted.
The whole `mousedown/touchstart` change started after I saw that some components would use `mousedown` to trigger the opening of an overlay. Instead, the manager should just listen to `tap` events, and overlays should remove themselves from the manager synchronously when they get closed, and add them asynchronously when they get opened.
If a component really has to open an overlay on `mousedown` (bad idea), it should take care the overlay doesn't get canceled by listening to `iron-overlay-canceled`, something like this http://jsbin.com/juziyow/3/edit?html,output
This also fixes #174.
=> Revert of #148

bower.json
Use `polymer v1.1.0`, which contains [the commit](https://github.com/Polymer/polymer/commit/3734c4d) that ensures the support of styles inside a `template` (see `iron-overlay-backdrop`). This should have been done in #186
=> use polymer v1.1.0

iron-overlay-behavior.html
Fixes #185, link the `simple-overlay` implementation in the docs, and explain the limitations of focus wrapping that wraps focus within the overlay's light dom.
=> link to simple-overlay example

iron-overlay-behavior.html
Fixes #201 by applying the focus a tick after `opened` changes. ~~Avoid calling `blur` when an overlay gets closed, since a closed overlay will be `display: none` hence non-focusable.~~
=> move focus a tick after opened changes

iron-overlay-behavior.html, iron-overlay-manager.html, test/iron-overlay-behavior.html
Fixes #182.
This PR decouples the adding/removing of an overlay into the manager from the focus management (now delegated to the overlay).
It makes the addition/removal of the overlay into the manager asynchronous in order to skip the event that might have caused the opened change.
Since the initial implementation, the adding of the overlay to the manager was synchronous, while its removal asynchronous. In addition, each overlay would [toggle asynchronously listeners](https://github.com/PolymerElements/iron-overlay-behavior/blob/v1.0.0/iron-overlay-behavior.html#L256) for `tap` and `keydown` events. These listeners were asynchronous to **avoid the execution of the callback during the same scope of the event that triggered the open/close** (e.g. `<button onclick="overlay.open()">`). Also, …
=> Async remove overlay

iron-focusables-helper.html, iron-overlay-behavior.html, test/index.html, test/iron-focusables-helper.html, test/iron-overlay-behavior.html, test/test-buttons-wrapper.html
Fixes #196, fixes #194, fixes #192.
`iron-focusables-helper` provides `getTabbableNodes` method, used to compute the tabbable elements within a specific node, searching both in the light and shadow dom, sorting by tabindex.
`_focusableNodes` has been changed to invoke this method. Tests have been updated to look for the focusable nodes once the overlays are opened (as it is required for a node to be visible in order to be considered tabbable).
Sorting by tabindex is a stable sort ([merge sort](https://www.youtube.com/watch?v=XaqR3G_NVoo)), since `Array.prototype.sort` is not guaranteed to be stable (fixes #209).
=> add iron-focusables-helper

iron-overlay-manager.html, test/iron-overlay-behavior.html
Fixes #225 by setting `useCapture = true` to the `tap` listener.
=> useCapture for tap events

iron-overlay-manager.html
use document.documentElement for Gestures and tap.
fixes https://github.com/PolymerElements/iron-overlay-behavior/issues/235
=> Update iron-overlay-manager.html with document.documentElement for taps

iron-overlay-behavior.html, test/iron-overlay-behavior.html
Restore focus only if activeElement was not changed by user interaction or other components.
Fixes https://github.com/PolymerElements/paper-dialog/issues/146
=> Fix restore focus

demo/index.html, iron-overlay-behavior.html, iron-overlay-manager.html, test/iron-overlay-behavior.html
Fixes #212.
`allow-click-through` property can be used to let click events go through overlays.
An overlay with `noCancelOnOutsideClick` would handle the click by not closing when the user clicks outside, while at the same time allow the overlay below it to handle the click (which might close if it's `noCancelOnOutsideClick = false`).
A concrete example is `paper-toast`, which should not close on click outside, but at the same time should allow overlays below it to close on outside click.
=> allow-click-through

demo/index.html, iron-overlay-behavior.html, test/iron-overlay-behavior-scroll-actions.html, test/test-scrollable.html
Fixes #254.
Listen for `scroll` events in all shadowRoots hosting the overlay, up to the main `document`.
Note that:
- if the scroll happens inside a shadowRoot that is not in the overlay's path, it won't be captured
- this doesn't guarantee preventing scrolls happening in any node different from `document`
e.g. see http://jsbin.com/wewemu/6/edit?html - scroll events happening in `scrollable_0` cannot be handled by the opened overlays, as they are contained in `scrollable_1`. For these cases, the user is expected to listen to the scroll events on different targets, and then calling `refit` or `cancel` on the overlay.
=> Capture scroll events

demo/index.html, iron-overlay-manager.html, test/iron-overlay-behavior.html
Fixes #124.
Given 2 overlays with backdrop, the last one to be opened should have the backdrop below it, meaning the backdrop should be rendered between the 2 overlays.
=> backdrop z-index below top overlay with-backdrop

iron-overlay-behavior.d.ts, iron-overlay-behavior.html, test/iron-overlay-behavior-scroll-actions.html
The comment above the line I changed says:
> Listen for scroll events in all shadowRoots hosting this overlay only when in **native ShadowDOM**
It's not possible to detect the native ShadowDOM by checking only `'attachShadow' in Element.prototype && 'getRootNode' in Element.prototype`:
Firefox | IE11
---|---
=> Fix __addScrollListeners for polyfilled browsers

iron-scroll-manager.html
Without, we get an undeclared variable here: https://github.com/PolymerElements/iron-overlay-behavior/blob/__auto_generated_3.0_preview/iron-scroll-manager.js#L163
=> Declare _boundScrollHandler so that modulizer sees it

iron-overlay-behavior.html
Fixes https://github.com/PolymerElements/paper-toast/issues/97.
Here the repro showing the fix - click on the input and notice the focus never leaves it http://output.jsbin.com/tuleyag/2/quiet
We don't need to invoke `_applyFocus` to the new overlay because restoring of the focus is already handled by 2 other code blocks: 
- `restoreFocusOnClose` logic already handles restoring the focus if the user didn't move it to another element (e.g. click on another button)
- `_onCaptureFocus` logic takes care of bringing back the focus to the overlay when needed.
Focus handling tests already cover most of these interactions, and adding a new test for this case would result in testing an implementation detail (e.g. "test that _applyFocus is not called").
=> no need to _applyFocus on new currentOverlay

iron-overlay-backdrop.html, iron-overlay-behavior.html, iron-scroll-manager.html, test/iron-overlay-behavior.html
Ignore the million commits, I had to commit to run modulizer; I'm going to have to squash them.
Added a declaration for `_boundScrollHandler` as modulizer does not play nice with namespaces and runs in strict mode.
Modulizer cannot work with getters in namespaces. It converts them to functions, so to keep backwards compatibility, I had to create a `getCurrentLockingElement ` function.
I had to wrap the `.bind(this)` in a try catch because modulizer would get rid of the `Polymer. IronScrollManager` namespace, but would replace the `this` in the `bind` with `Polymer. IronScrollManager` which would always fail. I could not get around this; it looks like modulizer would read the closure.
I added some `var`s for strict mode
I added commas to the end of each property definition in the …
=> Fix modulizer

iron-overlay-behavior.js, test/iron-overlay-behavior.html
=> Update `_focusableNodes` before every focus wrapping check.

iron-focusables-helper.js
This is easier for closure compiler to read and optimize correctly, and is otherwise a no-op.
Similar to the change we made to the other helper in this repo.
Internalized as cl/218204453
=> Make IronFocusablesHelper a singleton

iron-overlay-manager.js, iron-scroll-manager.js
`@private` doesn't make sense as a visibility for an exported binding, and jscompiler will begin warning about this soon.
Downstreamed as cl/236669868 and cl/236397214
=> Use @package visibility for private exports.

iron-overlay-manager.html
Replace call to deprecated Polymer.Gestures.add function with Polymer.Gestures.addListener.
Fixes a Closure compiler error (JSC_DEPRECATED_PROP_REASON).
=> Update deprecated function call

iron-overlay-behavior.js, iron-scroll-manager.js
- Guard against CE polyfill's lack of reactions stack in `#detached`.
- Add a cast for Closure.
=> Sync some internal changes.

iron-overlay-behavior.js, test/has-shadow-overlay.js, test/iron-overlay-behavior.html
Before this PR, focus was only restored when closing an overlay if there was no focused element (or `<body>`) or the focused element was a shadow-including descendant of the overlay. This prevented focus from being restored if the focused element inside the overlay was distributed into the overlay through a slot:
```html
<outer-element>
#shadow-root
<element-with-iron-overlay-behavior>
<slot name="in-overlay">
</element-with-iron-overlay-behavior>
#/shadow-root
<input slot="in-overlay">
</outer-element>
```
This PR changes the test to check that the focused node is any descendant of the overlay in the *flattened* tree.
=> Restore focus if the node with focus in the overlay is distributed into it.

README.md, iron-focusables-helper.js, package-lock.json, package.json
addresses but not f1x #282 and PolymerElements/paper-dialog#125
=> feat: add [iron-focusable] to mark as focusable
